Imports System
Imports System.Collections.Generic

Namespace Searcher.Parser.Setting.HelpDopSetting
	Friend Class country
		Private GoogleDBCountry As Dictionary(Of String, String)

		Private BingDBCountry As Dictionary(Of String, String)

        Public Sub New()
            Me.GoogleDBCountry = New Dictionary(Of String, String)() From
            {
                {"Abkhazia", "AB"},
                {"Australia", "AU"},
                {"Austria", "AT"},
                {"Azerbaijan", "AZ"},
                {"Albania", "AL"},
                {"Algeria", "DZ"},
                {"American Samoa", "AS"},
                {"Anguilla", "AI"},
                {"Angola", "AO"},
                {"Andorra", "AD"},
                {"Antarctica", "AQ"},
                {"Antigua and Barbuda", "AG"},
                {"Argentina", "AR"},
                {"Armenia", "AM"},
                {"Aruba", "AW"},
                {"Afghanistan", "AF"},
                {"Bahamas", "BS"},
                {"Bangladesh", "BD"},
                {"Barbados", "BB"},
                {"Bahrain", "BH"},
                {"Belarus", "BY"},
                {"Belize", "BZ"},
                {"Belgium", "BE"},
                {"Benin", "BJ"},
                {"Bermuda", "BM"},
                {"Bulgaria", "BG"},
                {"Bolivia", "BO"},
                {"Bonaire", "BQ"},
                {"Bosnia and Herz.", "BA"},
                {"Botswana", "BW"},
                {"Brazil", "BR"},
                {"British IOT", "IO"},
                {"Brunei Darussalam", "BN"},
                {"Burkina Faso", "BF"},
                {"Burundi", "BI"},
                {"Bhutan", "BT"},
                {"Vanuatu", "VU"},
                {"Hungary", "HU"},
                {"Venezuela", "VE"},
                {"Virgin Islands, British", "VG"},
                {"Virgin Islands, U.S.", "VI"},
                {"Vietnam", "VN"},
                {"Gabon", "GA"},
                {"Haiti", "HT"},
                {"Guyana", "GY"},
                {"Gambia", "GM"},
                {"Ghana", "GH"},
                {"Guadeloupe", "GP"},
                {"Guatemala", "GT"},
                {"Guinea", "GN"},
                {"Guinea-Bissau", "GW"},
                {"Germany", "DE"},
                {"Guernsey", "GG"},
                {"Gibraltar", "GI"},
                {"Honduras", "HN"},
                {"Hong Kong", "HK"},
                {"Grenada", "GD"},
                {"Greenland", "GL"},
                {"Greece", "GR"},
                {"Georgia", "GE"},
                {"Guam", "GU"},
                {"Denmark", "DK"},
                {"Jersey", "JE"},
                {"Djibouti", "DJ"},
                {"Dominica", "DM"},
                {"Dominican Republic", "DO"},
                {"Egypt", "EG"},
                {"Zambia", "ZM"},
                {"Western Sahara", "EH"},
                {"Zimbabwe", "ZW"},
                {"Israel", "IL"},
                {"India", "IN"},
                {"Indonesia", "ID"},
                {"Jordan", "JO"},
                {"Iraq", "IQ"},
                {"Iran", "IR"},
                {"Ireland", "IE"},
                {"Iceland", "IS"},
                {"Spain", "ES"},
                {"Italy", "IT"},
                {"Yemen", "YE"},
                {"Cape Verde", "CV"},
                {"Kazakhstan", "KZ"},
                {"Cambodia", "KH"},
                {"Cameroon", "CM"},
                {"Canada", "CA"},
                {"Qatar", "QA"},
                {"Kenya", "KE"},
                {"Cyprus", "CY"},
                {"Kyrgyzstan", "KG"},
                {"Kiribati", "KI"},
                {"China", "CN"},
                {"Cocos Islands", "CC"},
                {"Colombia", "CO"},
                {"Comoros", "KM"},
                {"Congo", "CG"},
                {"Congo, Democratic", "CD"},
                {"Korea, Democratic", "KP"},
                {"Korea", "KR"},
                {"Costa Rica", "CR"},
                {"Cote d'Ivoire", "CI"},
                {"Cuba", "CU"},
                {"Kuwait", "KW"},
                {"Curaçao", "CW"},
                {"Lao People's", "LA"},
                {"Latvia", "LV"},
                {"Lesotho", "LS"},
                {"Lebanon", "LB"},
                {"Libyan Arab", "LY"},
                {"Liberia", "LR"},
                {"Liechtenstein", "LI"},
                {"Lithuania", "LT"},
                {"Luxembourg", "LU"},
                {"Mauritius", "MU"},
                {"Mauritania", "MR"},
                {"Madagascar", "MG"},
                {"Mayotte", "YT"},
                {"Macao", "MO"},
                {"Malawi", "MW"},
                {"Malaysia", "MY"},
                {"Mali", "ML"},
                {"US Minor", "UM"},
                {"Maldives", "MV"},
                {"Malta", "MT"},
                {"Morocco", "MA"},
                {"Martinique", "MQ"},
                {"Marshall Islands", "MH"},
                {"Mexico", "MX"},
                {"Micronesia", "FM"},
                {"Mozambique", "MZ"},
                {"Moldova", "MD"},
                {"Monaco", "MC"},
                {"Mongolia", "MN"},
                {"Montserrat", "MS"},
                {"Myanmar", "MM"},
                {"Namibia", "NA"},
                {"Nauru", "NR"},
                {"Nepal", "NP"},
                {"Niger", "NE"},
                {"Nigeria", "NG"},
                {"Netherlands", "NL"},
                {"Nicaragua", "NI"},
                {"Niue", "NU"},
                {"New Zealand", "NZ"},
                {"New Caledonia", "NC"},
                {"Norway", "NO"},
                {"UAE", "AE"},
                {"Oman", "OM"},
                {"Bouvet Island", "BV"},
                {"Isle of Man", "IM"},
                {"Norfolk Island", "NF"},
                {"Christmas Island", "CX"},
                {"Heard and McDonald", "HM"},
                {"Cayman Islands", "KY"},
                {"Cook Islands", "CK"},
                {"Turks Islands", "TC"},
                {"Pakistan", "PK"},
                {"Palau", "PW"},
                {"Palestinian", "PS"},
                {"Panama", "PA"},
                {"Holy See", "VA"},
                {"Papua New Guinea", "PG"},
                {"Paraguay", "PY"},
                {"Peru", "PE"},
                {"Pitcairn", "PN"},
                {"Poland", "PL"},
                {"Portugal", "PT"},
                {"Puerto Rico", "PR"},
                {"Macedonia", "MK"},
                {"Reunion", "RE"},
                {"Russian Federation", "RU"},
                {"Rwanda", "RW"},
                {"Romania", "RO"},
                {"Samoa", "WS"},
                {"San Marino", "SM"},
                {"Sao Tome", "ST"},
                {"Saudi Arabia", "SA"},
                {"Swaziland", "SZ"},
                {"Saint Helena", "SH"},
                {"N. Mariana Islands", "MP"},
                {"Saint Barthélemy", "BL"},
                {"Saint Martin", "MF"},
                {"Senegal", "SN"},
                {"Saint Vincent", "VC"},
                {"Saint Lucia", "LC"},
                {"Saint Kitts", "KN"},
                {"Saint Pierre", "PM"},
                {"Serbia", "RS"},
                {"Seychelles", "SC"},
                {"Singapore", "SG"},
                {"Sint Maarten", "SX"},
                {"Syrian Arab", "SY"},
                {"Slovakia", "SK"},
                {"Slovenia", "SI"},
                {"United Kingdom", "GB"},
                {"United States", "US"},
                {"Solomon Islands", "SB"},
                {"Somalia", "SO"},
                {"Sudan", "SD"},
                {"Suriname", "SR"},
                {"Sierra Leone", "SL"},
                {"Tajikistan", "TJ"},
                {"Thailand", "TH"},
                {"Taiwan", "TW"},
                {"Tanzania", "TZ"},
                {"Timor-Leste", "TL"},
                {"Togo", "TG"},
                {"Tokelau", "TK"},
                {"Tonga", "TO"},
                {"Trinidad and Tobago", "TT"},
                {"Tuvalu", "TV"},
                {"Tunisia", "TN"},
                {"Turkmenistan", "TM"},
                {"Turkey", "TR"},
                {"Uganda", "UG"},
                {"Uzbekistan", "UZ"},
                {"Ukraine", "UA"},
                {"Wallis and Futuna", "WF"},
                {"Uruguay", "UY"},
                {"Faroe Islands", "FO"},
                {"Fiji", "FJ"},
                {"Philippines", "PH"},
                {"Finland", "FI"},
                {"Falkland Islands", "FK"},
                {"France", "FR"},
                {"French Guiana", "GF"},
                {"French Polynesia", "PF"},
                {"French Southern", "TF"},
                {"Croatia", "HR"},
                {"Central African", "CF"},
                {"Chad", "TD"},
                {"Montenegro", "ME"},
                {"Czech Republic", "CZ"},
                {"Chile", "CL"},
                {"Switzerland", "CH"},
                {"Sweden", "SE"},
                {"Svalbard", "SJ"},
                {"Sri Lanka", "LK"},
                {"Ecuador", "EC"},
                {"Equatorial Guinea", "GQ"},
                {"Åland Islands", "AX"},
                {"El Salvador", "SV"},
                {"Eritrea", "ER"},
                {"Estonia", "EE"},
                {"Ethiopia", "ET"},
                {"South Africa", "ZA"},
                {"South Georgia", "GS"},
                {"South Ossetia", "OS"},
                {"South Sudan", "SS"},
                {"Jamaica", "JM"},
                {"Japan", "JP"}
            }
            Me.BingDBCountry = New Dictionary(Of String, String)() From
            {
                {"Argentina", "es-AR"},
                {"Australia", "en-AU"},
                {"Austria", "de-AT"},
                {"Belgium-Dutch", "nl-BE"},
                {"Belgium-French", "fr-BE"},
                {"Brazil", "pt-BR"},
                {"Canada-English", "en-CA"},
                {"Canada-French", "fr-CA"},
                {"France", "fr-FR"},
                {"Germany", "de-DE"},
                {"Hong Kong S.A.R.", "zh-HK"},
                {"India", "en-IN"},
                {"Indonesia", "en-ID"},
                {"Italy", "it-IT"},
                {"Japan", "ja-JP"},
                {"Korea", "ko-KR"},
                {"Malaysia", "en-MY"},
                {"Mexico", "es-MX"},
                {"Netherlands", "nl-NL"},
                {"Norway", "nb-NO"},
                {"China", "zh-CN"},
                {"Poland", "pl-PL"},
                {"Russia", "ru-RU"},
                {"Saudi Arabia", "ar-SA"},
                {"South Africe", "en-ZA"},
                {"Spain", "es-ES"},
                {"Sweden", "sv-SE"},
                {"Switzerland", "fr-CH"},
                {"Switzerland - German", "de-CH"},
                {"Taiwan", "zh-TW"},
                {"Turkey", "tr-TR"},
                {"United Kingdom", "en-GB"},
                {"United States-English", "en-US"},
                {"United States-Spanish", "es-US"}
            }
        End Sub

        Public Function GetCountry(ByVal Country As String, ByVal Service As Integer) As String
			Dim value As String
			If (Service = 0) Then
				For Each googleDBCountry As KeyValuePair(Of String, String) In Me.GoogleDBCountry
					If (googleDBCountry.Key <> Country) Then
						Continue For
					End If
					value = googleDBCountry.Value
					Return value
				Next
			End If
			If (Service = 1) Then
				For Each bingDBCountry As KeyValuePair(Of String, String) In Me.BingDBCountry
					If (bingDBCountry.Key <> Country) Then
						Continue For
					End If
					value = bingDBCountry.Value
					Return value
				Next
			End If
			Return ""
		End Function
	End Class
End Namespace